name: mentu_app
description: Mentu - app completa (local backend)
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  http: ^1.2.1
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  uuid: ^4.5.0
  path: ^1.9.1
  sqflite: ^2.4.2
  riverpod: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
